name: click_clinic
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.13.0
  flutter_spinkit: "^4.1.2"
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.4+1
  firebase_core: ^0.4.0+8
  firebase_storage: ^3.0.4
  firebase_database: ^3.1.1
  provider: ^3.1.0 
  splashscreen: ^1.2.0
  #GeoLocation packages
  geoflutterfire: ^2.1.0
  location: ^3.0.1
  geolocator: ^5.3.0
  google_maps_flutter: ^0.5.22
  permission_handler: ^4.4.0+hotfix.2
  image_picker: ^0.6.5+2
  getflutter: ^1.0.4
  shared_preferences: ^0.5.2
  cupertino_icons: ^0.1.2
  #url_launcher: ^5.4.2
  csv: ^4.0.3
  responsive_widgets: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icones/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeui.ttf
    - family: CenturyGothic-Bold
      fonts:
        - asset: assets/fonts/gothicb.ttf


  # see https://flutter.dev/custom-fonts/#from-packages
